#!/usr/bin/with-contenv bash

_term() {
	echo "Caught SIGTERM for rtorrent!"
	# Get rtorrent PID
	R_PID=`pgrep rtorrent`
	# Send kill signal to rtorrent
	# https://github.com/rakshasa/rtorrent/blob/master/src/main.cc#L199
	kill -s SIGINT ${R_PID} 2>/dev/null
	# Wait for rtorrent to exit
	while kill -0 ${R_PID}; do
		echo "# ${R_PID} Waiting for rtorrent to quit"
		sleep 1
	done
}

trap _term SIGTERM

RTORRENT_LOCK="/detach_sess/.rtorrent"
echo "# Checking rtorrent session lock ${RTORRENT_LOCK}"
# Check if session lock wasn't deleted
if [ -S "${RTORRENT_LOCK}" ] && ! pgrep rtorrent > /dev/null; then
	echo "# Removing rtorrent session lock ${RTORRENT_LOCK}"
	rm -f "${RTORRENT_LOCK}"
fi

echo "# Starting rtorrent."

dtach -N "${RTORRENT_LOCK}" \
	s6-setuidgid abc /usr/bin/rtorrent \
		-n -o import=/config/rtorrent/rtorrent.rc &

DTACH_PID=$!
sleep 1

echo "# rtorrent waiting for ${DTACH_PID}"
wait ${DTACH_PID}
echo "# rtorrent waited for ${DTACH_PID}"

sleep 1
